name: Build macOS Release

on: [ push, pull_request ]

jobs:
  build-macos:
    name: Build macOS Release
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version-file: pubspec.yaml
      - name: Install dependencies
        run: flutter pub get
      - name: Build macOS release
        run: flutter build macos --release
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-release
          path: build/macos/Build/Products/Release/
          overwrite: true
          compression-level: 9
          retention-days: 90