name: Build Windows Release

on: [ push, pull_request ]

jobs:
  windows-build:
    name: Build Windows Release
    runs-on: windows-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
          flutter-version: 3.44.8

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Cache Windows build artifacts
        uses: actions/cache@v4
        with:
          path: build/windows
          key: ${{ runner.os }}-flutter-build-${{ hashFiles('pubspec.lock', 'pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-build-

      - name: Build Windows release
        run: flutter build windows --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: build/windows/x64/runner/Release
          overwrite: true
          compression-level: 9
          retention-days: 90
